config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions: 'admin/sessions',
    registrations: 'admin/registrations'
  }
  devise_for :customers, controllers: {
    sessions: 'customer/sessions',
    registrations: 'customer/registrations'
  }

  # ルート追加（顧客用と管理者用）
  devise_scope :customer do
    post 'customers/guest_sign_in', to: 'customer/sessions#guest_sign_in', as: :guest_customer_sign_in
  end
  
  devise_scope :admin do
    post 'admins/guest_sign_in', to: 'admin/sessions#guest_sign_in', as: :guest_admin_sign_in
  end
  
  root to: 'pages#home'
  namespace :admin do
    root to: 'pages#home'
    resources :products, only: %i[index show new create edit update destroy]
    resources :orders, only: %i[show update]
    resources :customers, only: %i[index show update]
    authenticate :admin do
      mount Sidekiq::Web => '/sidekiq'
    end
  end

  scope module: :customer do
    resources :products, only: %i[index show] do
      resources :reviews, only: %i[index create]
    end
    resources :contacts, only: %i[new create]
    resources :cart_items, only: %i[index create destroy] do
      member do
        patch 'increase'
        patch 'decrease'
      end
    end
    resources :checkouts, only: [:create]
    post '/webhooks/stripe', to: 'webhooks#stripe'
    resources :orders, only: %i[index show] do
      collection do
        get 'success'
      end
    end
    resources :customers do
      collection do
        get 'confirm_withdraw'
        patch 'withdraw'
      end
    end
  end
  
  get '/up/', to: 'up#index', as: :up
  get '/up/databases', to: 'up#databases', as: :up_databases
  match '/500', to: 'application#render500', via: :all
  match '/404', to: 'application#render404', via: :all
  get 'test_render500', to: 'error/errors#test_render500'
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
  scope :latest, -> { order(created_at: :desc) }
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :product

  def line_total
    product.price * quantity
  end
end

app/models/contact_form.rb
class ContactForm
  include ActiveModel::Model

  attr_accessor :subject, :name, :content

  validates :subject, presence: true
  validates :name, presence: true
  validates :content, presence: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  with_options presence: true do
    validates :name
    validates :status
  end
  enum status: {
    "通常": 0,
    "退会済": 1,
    "利用停止": 2
  }
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :reviews, dependent: :destroy

  def line_items_checkout
    cart_items.map do |cart_item|
      {
        quantity: cart_item.quantity,
        price_data: {
          currency: 'jpy',
          unit_amount: cart_item.product.price,
          product_data: {
            name: cart_item.product.name,
            metadata: {
              product_id: cart_item.product_id
            }
          }
        }
      }
    end
  end

  def active_for_authentication?
    super && (status == '通常')
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  enum status: {
    入金待ち: 0,
    入金確認: 1,
    出荷済み: 2,
    配送中: 3,
    配達済み: 4
  }
  has_many :order_details, dependent: :destroy

  scope :waiting_payment, -> { where(status: '入金待ち') }
  scope :confirm_payment, -> { where(status: '入金確認') }
  scope :shipped, -> { where(status: '出荷済み') }
  scope :out_of_delivery, -> { where(status: '配送中') }
  scope :delivered, -> { where(status: '配達済み') }

  scope :created_today, -> { where('orders.created_at >= ?', Time.zone.now.beginning_of_day) }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  paginates_per 10
  with_options presence: true do
    validates :name
    validates :description
    validates :price
    validates :stock
    validates :image
  end
  has_one_attached :image
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  has_many :reviews, dependent: :destroy

  def avg_score
    if reviews.empty?
      0.0
    else
      reviews.average(:score).round(1).to_f
    end
  end

  def review_score_percentage
    if reviews.empty?
      0.0
    else
      reviews.average(:score).round(1).to_f * 100 / 5
    end
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :customer
  belongs_to :product

  validates :score, presence: true
  validates :content, presence: true
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_order

  def show; end

  def update
    @order.update(order_params)
    redirect_to admin_root_path, notice: '注文ステータスが正常に更新されました。'
  end

  private

  def set_order
    @order = Order.find(params[:id])
  end

  def order_params
    params.require(:order).permit(:status)
  end
end

app/controllers/admin/pages_controller.rb
class Admin::PagesController < ApplicationController
  before_action :authenticate_admin!

  def home
    @orders, @selected = get_orders(params)
    @orders = @orders.page(params[:page]).per(10) # 検索結果にページネーションを適用
    today_orders = Order.created_today
    @today_total_orders = total_orders(today_orders)
    @today_total_sales = total_sales(today_orders)
  end

  private

  def get_orders(params)
    if !params[:status].present? || !Order.statuses.keys.to_a.include?(params[:status])
      return [Order.eager_load(:customer).latest,
              'all']
    end

    get_by_enum_value(params[:status])
  end

  def get_by_enum_value(status)
    case status
    when '入金待ち'
      [Order.waiting_payment.eager_load(:customer).latest, '入金待ち']
    when '入金確認'
      [Order.confirm_payment.eager_load(:customer).latest, '入金確認']
    when '出荷済み'
      [Order.shipped.eager_load(:customer).latest, '出荷済み']
    when '配送中'
      [Order.out_of_delivery.eager_load(:customer).latest, '配送中']
    when '配達済み'
      [Order.delivered.eager_load(:customer).latest, '配達済み']
    end
  end

  def total_orders(orders)
    orders.count
  end

  def total_sales(orders)
    orders.sum(:billing_amount)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from StandardError, with: :render500
  rescue_from ActiveRecord::RecordNotFound, with: :render404

  def after_sign_in_path_for(resource)
    if resource.is_a?(Admin)
      admin_root_path # 管理者の場合
    else
      products_path   # 一般ユーザーの場合
    end
  end

  def render500(error = nil)
    Rails.logger.error("❌#{error.message}") if error&.message
    render template: 'errors/error500', layout: 'application', status: :internal_server_error
  end

  def render404(error = nil)
    Rails.logger.error("❌#{error.message}") if error&.message
    render template: 'errors/error404', layout: 'application', status: :not_found
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home; end
end

app/controllers/up_controller.rb
class UpController < ApplicationController
  def index
    head :ok
  end

  def databases
    RedisConn.current.ping
    ActiveRecord::Base.connection.execute('SELECT 1')

    head :ok
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/customer/cart_items_helper.rb
module Customer::CartItemsHelper
  def total_quantity(cart_items)
    cart_items.sum(:quantity)
  end
end

app/helpers/customer/products_helper.rb
module Customer::ProductsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/admin/pages/home.html.erb
<div class="mb-8 text-center">
  <span class="text-3xl font-bold">
    注文履歴一覧
  </span>
</div>

<div class="w-full mx-auto p-6">
  <div class="flex flex-wrap">
    <div class="w-full max-w-full px-3 mb-6 md:w-1/2 sm:flex-none">
      <div class="flex flex-col min-w-0 break-words bg-white shadow-md rounded-xl bg-clip-border">
        <div class="p-4">
          <div class="flex justify-center items-center">
            <div class="w-2/3 max-w-full px-3">
              <div>
                <p class="mb-0 font-sans font-semibold leading-normal text-sm">本日の売上額</p>
                <p class="mb-0 font-bold text-xl">
                  <%= number_to_currency(@today_total_sales, unit: "¥", strip_insignificant_zeros: true) %>
                </p>
              </div>
            </div>
            <div class="px-3 text-right basis-1/3 flex items-center justify-end">
              <div class="inline-block w-12 h-12 text-center rounded-lg bg-gradient-to-tl from-purple-700 to-pink-500">
                <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" class="w-full p-3 text-white" viewBox="0 0 16 16">
                  <path d="M4 11H2v3h2v-3zm5-4H7v7h2V7zm5-5v12h-2V2h2zm-2-1a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h2a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1h-2zM6 7a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v7a1 1 0 0 1-1 1H7a1 1 0 0 1-1-1V7zm-5 4a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v3a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1v-3z"/>
                </svg>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="w-full max-w-full px-3 mb-6 md:w-1/2 sm:flex-none">
      <div class="flex flex-col min-w-0 break-words bg-white shadow-md rounded-xl bg-clip-border">
        <div class="p-4">
          <div class="flex justify-center items-center">
            <div class="w-2/3 max-w-full px-3">
              <div>
                <p class="mb-0 font-sans font-semibold leading-normal text-sm">本日の注文数</p>
                <p class="mb-0 font-bold text-xl">
                  <%= @today_total_orders %>
                </p>
              </div>
            </div>
            <div class="px-3 text-right basis-1/3 flex items-center justify-end">
              <div class="inline-block w-12 h-12 text-center rounded-lg bg-gradient-to-tl from-purple-700 to-pink-500">
                <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" class="w-full p-3 text-white" viewBox="0 0 16 16">
                  <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 13 12H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l1.313 7h8.17l1.313-7H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
                </svg>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<%= form_with url: admin_root_path, method: :get, class: "px-9", local: true  do |f|  %>
  <div class="flex items-center">
    <h1 class="text-xl font-semibold leading-5 text-gray-800">注文ステータス</h1>
    <%= f.select :status, options_for_select(Order.statuses.keys.to_a, @selected), { prompt: "全て" }, {class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block p-3 appearance-none ml-4"} %>
    <%= f.submit "検索する", class: "inline-flex items-center justify-center rounded-md bg-indigo-500 p-3 text-white duration-100 ease-in-out hover:bg-indigo-600 focus:outline-none ml-4 cursor-pointer" %>
  </div>
<% end %>

<div class="flex flex-wrap p-6">
  <div class="flex-none w-full max-w-full px-3">
    <div class="relative flex flex-col min-w-0 mb-6 break-words bg-white border-0 border-transparent border-solid rounded-2xl bg-clip-border">
      <div class="flex-auto px-0 pt-0 pb-2">
        <div class="p-0 overflow-x-auto">
          <table class="items-center w-full mb-0 align-top border-gray-200 text-slate-500">
            <thead class="align-bottom">
              <tr>
                <th class="px-6 py-3 font-bold text-left uppercase align-middle bg-transparent border-b border-gray-200 shadow-none text-lg border-b-solid tracking-none whitespace-nowrap text-slate-400">メールアドレス</th>
                <th class="px-6 py-3 pl-2 font-bold text-left uppercase align-middle bg-transparent border-b border-gray-200 shadow-none text-lg border-b-solid tracking-none whitespace-nowrap text-slate-400">請求金額</th>
                <th class="px-6 py-3 font-bold text-center uppercase align-middle bg-transparent border-b border-gray-200 shadow-none text-lg border-b-solid tracking-none whitespace-nowrap text-slate-400">注文ステータス</th>
                <th class="px-6 py-3 font-bold text-center uppercase align-middle bg-transparent border-b border-gray-200 shadow-none text-lg border-b-solid tracking-none whitespace-nowrap text-slate-400">注文日時</th>
                <th class="px-6 py-3 font-semibold capitalize align-middle bg-transparent border-b border-gray-200 border-solid shadow-none tracking-none whitespace-nowrap text-slate-400"></th>
              </tr>
            </thead>
            <tbody>
              <% @orders.each do |order| %>
                <tr>
                  <td class="p-2 align-middle bg-transparent border-b whitespace-nowrap shadow-transparent">
                    <div class="flex px-2 py-1">
                      <div class="flex flex-col justify-center">
                        <p class="mb-0 leading-normal text-md"><%= order.customer.email %></p>
                      </div>
                    </div>
                  </td>
                  <td class="p-2 align-middle bg-transparent border-b whitespace-nowrap shadow-transparent">
                    <p class="font-semibold leading-tight text-md"><%= number_to_currency(order.billing_amount, unit: "¥", strip_insignificant_zeros: true) %></p>
                  </td>
                  <td class="p-2 leading-normal text-center align-middle bg-transparent border-b text-sm whitespace-nowrap shadow-transparent">
                    <span class="bg-blue-100 text-blue-800 text-xs font-semibold p-2 rounded"><%= order.status %></span>
                  </td>
                  <td class="p-2 text-center align-middle bg-transparent border-b whitespace-nowrap shadow-transparent">
                    <span class="font-semibold leading-tight text-md"><%= l order.created_at, format: :short %></span>
                  </td>
                  <td class="p-2 align-middle bg-transparent border-b whitespace-nowrap shadow-transparent">
                    <%= link_to admin_order_path(order), class: "font-semibold leading-tight text-sm text-slate-400" do %>
                      詳細
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

<%= paginate @orders %>

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div class="bg-orange-100 border-l-4 border-orange-500 text-orange-700 p-4 mb-5" role="alert">
    <p class="font-bold">
      <%= I18n.t("activerecord.errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </p>
    <ul>
      <% resource.errors.messages.values.flatten.uniq.each do |message| %>
        <li><%= message.gsub(/^[^ ]+\s/, '') %></li> <!-- フィールド名を削除してメッセージのみ表示 -->
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "ログイン", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "新規登録", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "確認メールが届きませんでしたか？", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "ロック解除のメールが届きませんでしたか？", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "#{OmniAuth::Utils.camelize(provider)}でログイン", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>