config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions: 'admin/sessions',
    registrations: 'admin/registrations'
  }
  devise_for :customers, controllers: {
    sessions: 'customer/sessions',
    registrations: 'customer/registrations'
  }

  # ルート追加（顧客用と管理者用）
  devise_scope :customer do
    post 'customers/guest_sign_in', to: 'customer/sessions#guest_sign_in', as: :guest_customer_sign_in
  end
  
  devise_scope :admin do
    post 'admins/guest_sign_in', to: 'admin/sessions#guest_sign_in', as: :guest_admin_sign_in
  end
  
  root to: 'pages#home'
  namespace :admin do
    root to: 'pages#home'
    resources :products, only: %i[index show new create edit update destroy]
    resources :orders, only: %i[show update]
    resources :customers, only: %i[index show update]
    authenticate :admin do
      mount Sidekiq::Web => '/sidekiq'
    end
  end

  scope module: :customer do
    resources :products, only: %i[index show] do
      resources :reviews, only: %i[index create]
    end
    resources :contacts, only: %i[new create]
    resources :cart_items, only: %i[index create destroy] do
      member do
        patch 'increase'
        patch 'decrease'
      end
    end
    resources :checkouts, only: [:create]
    post '/webhooks/stripe', to: 'webhooks#stripe'
    resources :orders, only: %i[index show] do
      collection do
        get 'success'
      end
    end
    resources :customers do
      collection do
        get 'confirm_withdraw'
        patch 'withdraw'
      end
    end
  end
  
  get '/up/', to: 'up#index', as: :up
  get '/up/databases', to: 'up#databases', as: :up_databases
  match '/500', to: 'application#render500', via: :all
  match '/404', to: 'application#render404', via: :all
  get 'test_render500', to: 'error/errors#test_render500'
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_customer, only: %i[show update]

  def index
    @customers = Customer.preload(:orders).latest
    @customers = Customer.page(params[:page]).per(10) # 1ページあたり10件を表示
  end

  def show; end

  def update
    @customer.update(customer_params)
    redirect_to admin_customers_path, notice: '会員ステータスが正常に更新されました。'
  end

  private

  def set_customer
    @customer = Customer.find(params[:id])
  end

  def customer_params
    params.require(:customer).permit(:status)
  end
end

app/controllers/customer/cart_items_controller.rb
class Customer::CartItemsController < ApplicationController
  before_action :authenticate_customer!
  before_action :set_cart_item, only: %i[increase decrease destroy]

  def index
    @cart_items = current_customer.cart_items
    @total = @cart_items.inject(0) { |sum, cart_item| sum + cart_item.line_total }
  end

  def create
    increase_or_create(params[:cart_item][:product_id])
    redirect_to cart_items_path, notice: '商品をカートに追加しました。'
  end

  def increase
    @cart_item.increment!(:quantity, 1)
    redirect_to request.referer, notice: 'カートの数量が増加しました。'
  end

  def decrease
    decrease_or_destroy(@cart_item)
    redirect_to request.referer, notice: 'カートの数量が減少しました。'
  end

  def destroy
    @cart_item.destroy
    redirect_to request.referer, notice: '1件のカートアイテムが削除されました。'
  end

  private

  def set_cart_item
    @cart_item = current_customer.cart_items.find(params[:id])
  end

  def increase_or_create(product_id)
    cart_item = current_customer.cart_items.find_by(product_id: product_id)
    if cart_item
      cart_item.increment!(:quantity, 1)
    else
      current_customer.cart_items.build(product_id: product_id).save
    end
  end

  def decrease_or_destroy(cart_item)
    if cart_item.quantity > 1
      cart_item.decrement!(:quantity, 1)
    else
      cart_item.destroy
    end
  end
end

app/controllers/customer/checkouts_controller.rb
class Customer::CheckoutsController < ApplicationController
  before_action :authenticate_customer!

  def create
    line_items = current_customer.line_items_checkout
    session = create_session(line_items)
    # Allow redirection to the host that is different to the current host
    redirect_to session.url, allow_other_host: true
  end

  private

  def create_session(line_items)
    Stripe::Checkout::Session.create(
      client_reference_id: current_customer.id,
      customer_email: current_customer.email,
      mode: 'payment',
      payment_method_types: ['card'],
      line_items: line_items, # 修正: line_itemsを直接渡す
      shipping_address_collection: {
        allowed_countries: ['JP']
      },
      shipping_options: [
        {
          shipping_rate_data: {
            type: 'fixed_amount',
            fixed_amount: {
              amount: 500,
              currency: 'jpy'
            },
            display_name: 'Single rate'
          }
        }
      ],
      success_url: "#{root_url}orders/success",
      cancel_url: "#{root_url}cart_items"
    )
  end
end

app/controllers/customer/confirmations_controller.rb
# frozen_string_literal: true

class Customer::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customer/contacts_controller.rb
class Customer::ContactsController < ApplicationController
  before_action :authenticate_customer! # ログイン済みの顧客のみアクセス可

  def new
    @contact_form = ContactForm.new
    render 'customer/contacts/new' # 明示的にビューを指定
  end

  def create
    @contact_form = ContactForm.new(contact_params)
    @customer = current_customer # 現在ログイン中の顧客を取得

    if @contact_form.valid?
      begin
        # 顧客向けのメールを送信
        ContactMailer.customer_contact_mail(@contact_form, @customer).deliver_now
        Rails.logger.debug "Validation Errors: #{@contact_form.errors.full_messages}"
        # 成功時にホーム画面に遷移し、メッセージを表示
        flash[:notice] = 'メールの送信に成功しました。'
        redirect_to root_path # ホーム画面にリダイレクト
      rescue StandardError
        flash.now[:alert] = 'メール送信に失敗しました。再度お試しください。'
        render 'customer/contacts/new', status: :unprocessable_entity
      end
    else
      render 'customer/contacts/new', status: :unprocessable_entity
    end
  end

  private

  def contact_params
    params.require(:contact_form).permit(:subject, :name, :content)
  end
end

app/controllers/customer/customers_controller.rb
class Customer::CustomersController < ApplicationController
  before_action :authenticate_customer!

  def confirm_withdraw; end

  def withdraw
    current_customer.update(status: '退会済')
    reset_session
    redirect_to root_path, notice: 'shopfizzから正常に退会しました'
  end
end

app/controllers/customer/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customer::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customer/orders_controller.rb
class Customer::OrdersController < ApplicationController
  before_action :authenticate_customer!

  def index
    @orders = current_customer.orders.latest.page(params[:page]).per(5) # 1ページあたり1件を表示
  end

  def show
    @order = current_customer.orders.find(params[:id])
  end

  def success; end
end

app/controllers/customer/passwords_controller.rb
# frozen_string_literal: true

class Customer::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customer/products_controller.rb
class Customer::ProductsController < ApplicationController
  before_action :authenticate_customer!, only: [:show]
  def index
    @products = Product.page(params[:page]).per(9) # 1ページあたり9件を表示
  end

  def show
    @product = Product.find(params[:id])
    @cart_item = CartItem.new
    @review = Review.new
  end
end

app/controllers/customer/registrations_controller.rb
# frozen_string_literal: true

class Customer::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customer/reviews_controller.rb
class Customer::ReviewsController < ApplicationController
  before_action :authenticate_customer!, only: [:create]
  def index
    @product = Product.find(params[:product_id])
    @reviews = @product.reviews
  end

  def create
    @product = Product.find_by(id: params[:product_id]) # find_byを使用して安全に取得
    if @product.nil?
      respond_to do |format|
        format.html { redirect_to root_path, alert: '商品が見つかりません。' }
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace('review_form', partial: 'shared/not_found',
                                                                   locals: { message: '商品が見つかりません。' })
        end
      end
      return
    end

    @review = @product.reviews.build(review_params)
    @review.customer_id = current_customer.id

    if @review.save
      respond_to do |format|
        format.html { redirect_to product_reviews_path(@product), notice: 'レビューの保存に成功しました。' }
        format.turbo_stream { redirect_to product_reviews_path(@product) }
      end
    else
      respond_to do |format|
        format.html { render 'customer/products/show', alert: 'レビューの保存に失敗しました。' }
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace('review_form', partial: 'customer/reviews/form',
                                                                   locals: { review: @review, product: @product })
        end
      end
    end
  end

  private

  def review_params
    params.require(:review).permit(:product_id, :score, :content)
  end
end

app/controllers/customer/sessions_controller.rb
# frozen_string_literal: true

class Customer::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  before_action :reject_invalid_customer, only: [:create]

  def guest_sign_in
    customer = Customer.find_or_create_by!(email: 'guest_customer@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = 'ゲスト顧客'
    end
    sign_in customer
    redirect_to root_path, notice: 'ゲスト顧客としてログインしました。'
  end

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  def reject_invalid_customer
    customer = Customer.find_by(email: params[:customer][:email])
    return unless customer

    return if customer.valid_password?(params[:customer][:password]) && customer.active_for_authentication?

    alert_message = if customer.status == '退会済'
                      'あなたはすでに退会しています'
                    else
                      'あなたのアカウントは停止されています'
                    end
    redirect_to request.referer, alert: alert_message
  end
end

app/controllers/customer/unlocks_controller.rb
# frozen_string_literal: true

class Customer::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customer/webhooks_controller.rb
class Customer::WebhooksController < ApplicationController
  skip_before_action :verify_authenticity_token

  def stripe
    payload = request.body.read
    sig_header = request.env['HTTP_STRIPE_SIGNATURE']
    endpoint_secret =  ENV['STRIPE_WEBHOOK_SECRET']
    event = nil

    begin
      event = Stripe::Webhook.construct_event(
        payload, sig_header, endpoint_secret
      )
    rescue JSON::ParserError => e
      # Invalid payload
      p e
      status 400
      return
    rescue Stripe::SignatureVerificationError => e
      # Invalid signature
      p e
      status 400
      return
    end

    case event.type
    when 'checkout.session.completed'
      session = event.data.object # sessionの取得
      customer = Customer.find(session.client_reference_id)
      return unless customer # 顧客が存在するか確認

      # トランザクション処理開始
      ApplicationRecord.transaction do
        order = create_order(session) # sessionを元にoedersテーブルにデータを挿入
        session_with_expand = Stripe::Checkout::Session.retrieve({ id: session.id, expand: ['line_items'] })
        session_with_expand.line_items.data.each do |line_item|
          create_order_details(order, line_item) # 取り出したline_itemをorder_detailsテーブルに登録
        end
      end

      # トランザクション処理終了
      customer.cart_items.destroy_all # 顧客のカート内商品を全て削除
      OrderMailer.complete(email: session.customer_details.email).deliver_later
      # レスポンスを返す
      render json: { message: 'Webhookが正常に受信され、処理されました。' }, status: :ok
    end
  end

  private

  def create_order(session)
    Order.create!({
                    customer_id: session.client_reference_id,
                    name: session.shipping_details.name,
                    postal_code: session.shipping_details.address.postal_code,
                    prefecture: session.shipping_details.address.state,
                    address1: session.shipping_details.address.line1,
                    address2: session.shipping_details.address.line2,
                    postage: session.shipping_options[0].shipping_amount,
                    billing_amount: session.amount_total,
                    status: '入金確認'
                  })
  end

  def create_order_details(order, line_item)
    product = Stripe::Product.retrieve(line_item.price.product)
    purchased_product = Product.find(product.metadata.product_id)
    raise ActiveRecord::RecordNotFound if purchased_product.nil?

    order_detail = order.order_details.create!({
                                                 product_id: purchased_product.id,
                                                 price: line_item.price.unit_amount,
                                                 quantity: line_item.quantity
                                               })
    purchased_product.update!(
      stock: purchased_product.stock - order_detail.quantity
    ) # 購入された商品の在庫数の更新
  end
end

app/helpers/customer/cart_items_helper.rb
module Customer::CartItemsHelper
  def total_quantity(cart_items)
    cart_items.sum(:quantity)
  end
end

app/helpers/customer/products_helper.rb
module Customer::ProductsHelper
end

app/views/admin/customers/index.html.erb
<div class="mb-8 text-center">
  <span class="text-3xl font-bold">
    顧客情報一覧
  </span>
</div>

<div class="flex flex-wrap p-6">
  <div class="flex-none w-full max-w-full px-3">
    <div class="relative flex flex-col min-w-0 mb-6 break-words bg-white border-0 border-transparent border-solid rounded-2xl bg-clip-border">
      <div class="flex-auto px-0 pt-0 pb-2">
        <div class="p-0 overflow-x-auto">
          <table class="items-center w-full mb-0 align-top border-gray-200 text-slate-500">
            <thead class="align-bottom">
              <tr>
                <th class="px-6 py-3 font-bold text-center uppercase align-middle bg-transparent border-b border-gray-200 shadow-none text-lg border-b-solid tracking-none whitespace-nowrap text-slate-400">顧客名</th>
                <th class="px-6 py-3 pl-2 font-bold text-center uppercase align-middle bg-transparent border-b border-gray-200 shadow-none text-lg border-b-solid tracking-none whitespace-nowrap text-slate-400">メールアドレス</th>
                <th class="px-6 py-3 font-bold text-center uppercase align-middle bg-transparent border-b border-gray-200 shadow-none text-lg border-b-solid tracking-none whitespace-nowrap text-slate-400">会員状況</th>
                <th class="px-6 py-3 font-bold text-center uppercase align-middle bg-transparent border-b border-gray-200 shadow-none text-lg border-b-solid tracking-none whitespace-nowrap text-slate-400">過去の注文</th>
                <th class="px-6 py-3 font-semibold capitalize align-middle bg-transparent border-b border-gray-200 border-solid shadow-none tracking-none whitespace-nowrap text-slate-400"></th>
              </tr>
            </thead>
            <tbody>
              <% @customers.each do |customer| %>
                <tr>
                  <td class="p-2 align-middle bg-transparent border-b whitespace-nowrap shadow-transparent">
                    <div class="flex px-2 py-1 justify-center items-center">
                      <div class="flex flex-col justify-center">
                        <p class="mb-0 leading-normal text-md text-center"><%= customer.name %></p>
                      </div>
                    </div>
                  </td>
                  <td class="p-2 align-middle bg-transparent border-b whitespace-nowrap shadow-transparent">
                    <p class="mb-0 leading-normal text-md text-center"><%= customer.email %></p>
                  </td>
                  <td class="p-2 leading-normal text-center align-middle bg-transparent border-b text-sm whitespace-nowrap shadow-transparent">
                    <% if customer.status === "通常" %>
                      <span class="bg-blue-100 text-blue-800 text-xs font-semibold p-2 rounded">通常</span>
                    <% elsif customer.status === "退会済" %>
                      <span class="bg-orange-100 text-orange-500 text-xs font-semibold p-2 rounded">退会済</span>
                    <% else %>
                      <span class="bg-red-100 text-red-800 text-xs font-semibold p-2 rounded">利用停止</span>
                    <% end %>
                  </td>
                  <td class="p-2 text-center align-middle bg-transparent border-b whitespace-nowrap shadow-transparent">
                    <span class="font-semibold leading-tight text-md"><%= customer.orders.size %></span>
                  </td>
                  <td class="p-2 align-middle bg-transparent border-b whitespace-nowrap shadow-transparent">
                    <%= link_to admin_customer_path(customer), class: "font-semibold leading-tight text-md text-md text-slate-400" do %>
                      詳細
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

<%= paginate @customers %>

app/views/admin/customers/show.html.erb
<div class="mb-8 text-center">
  <span class="text-3xl font-bold">
    顧客情報詳細
  </span>
</div>

<div class="px-6">
  <div class="flex justify-start item-start space-y-2 flex-col mb-8">
    <h1 class="text-3xl lg:text-4xl font-semibold leading-7 lg:leading-9 text-gray-800">顧客 ID #<%= @customer.id %></h1>
    <p class="text-base font-medium leading-6 text-gray-600">作成日時: <%= l @customer.created_at, format: :short %></p>
    <p class="text-base font-medium leading-6 text-gray-600">更新日時: <%= l @customer.updated_at, format: :short %></p>
  </div> 
  <div class="flex flex-col xl:flex-row jusitfy-center  w-full xl:space-x-8 space-y-4 md:space-y-6 xl:space-y-0">
    <div class="flex flex-col justify-start items-start w-full space-y-4 xl:space-y-8">
      <div class="bg-gray-50 w-full h-fit px-4 py-6 md:p-6 xl:p-8">
        <h3 class="text-xl font-semibold leading-5 text-gray-800">顧客名</h3>
        <div class="flex justify-center w-full xl:justify-start items-center space-x-4 py-8 border-b border-gray-200">
          <div class="flex justify-start items-start flex-col space-y-2">
            <p class="text-base font-semibold leading-4 text-left text-gray-800">
              <%= @customer.name %>
            </p>
            <p class="text-sm leading-5 text-gray-600">
              <%= @customer.orders.count %> 件の過去注文
            </p>
          </div>
        </div>
        <div class="flex justify-center text-gray-800 xl:justify-start items-center space-x-4 py-4 border-b border-gray-200 w-full">
          <svg class="w-5" viewBox="0 0 8 6" xmlns="http://www.w3.org/2000/svg">
            <path d="m0 0h8v6h-8zm.75 .75v4.5h6.5v-4.5zM0 0l4 3 4-3v1l-4 3-4-3z"/>
          </svg>
          <p class="text-sm"><%= @customer.email %></p>
        </div>
      </div>
      <div class="flex justify-center flex-col md:flex-row items-stretch w-full space-y-4 md:space-y-0 md:space-x-6 xl:space-x-8">
        <div class="px-4 py-6 md:p-6 xl:p-8 w-full bg-gray-50 space-y-6">
          <h3 class="text-xl font-semibold leading-5 text-gray-800">会員ステータス</h3>
          <p>現在の状況:
            <% if @customer.status === "通常" %>
              <span class="bg-blue-100 text-blue-800 text-xs font-semibold p-2 rounded">通常</span>
            <% elsif @customer.status === "退会済" %>
              <span class="bg-orange-100 text-orange-500 text-xs font-semibold p-2 rounded">退会済</span>
            <% else %>
              <span class="bg-red-100 text-red-800 text-xs font-semibold p-2 rounded">利用停止</span>
            <% end %>
          </p>
          <%= form_with model: @customer, url: admin_customer_path(@customer), local: true  do |f|  %>
            <div class="mb-6">
              <%= f.select :status, Customer.statuses.keys.to_a, {}, {class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-3 appearance-none"} %>
            </div>
            <%= f.submit "会員ステータス更新", class: "inline-flex w-full items-center justify-center rounded-md bg-indigo-500 p-3 text-white duration-100 ease-in-out hover:bg-indigo-600 focus:outline-none cursor-pointer" %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="flex flex-col justify-start items-start bg-gray-50 px-4 py-6 md:py-6 md:p-6 xl:p-8 w-full overflow-x-auto">
    <h3 class="mb-4 text-xl font-semibold leading-5 text-gray-800">注文履歴</h3>
      <% if @customer.orders.size > 0 %>
      <table class="items-center w-full mb-0 align-top border-gray-200 text-slate-500">
        <thead class="align-bottom">
          <tr>
            <th class="px-6 py-3 pl-2 font-bold text-left uppercase align-middle bg-transparent border-b border-gray-200 shadow-none text-lg border-b-solid tracking-none whitespace-nowrap text-slate-400">請求金額</th>
            <th class="px-6 py-3 font-bold text-center uppercase align-middle bg-transparent border-b border-gray-200 shadow-none text-lg border-b-solid tracking-none whitespace-nowrap text-slate-400">注文ステータス</th>
            <th class="px-6 py-3 font-bold text-center uppercase align-middle bg-transparent border-b border-gray-200 shadow-none text-lg border-b-solid tracking-none whitespace-nowrap text-slate-400">注文日</th>
            <th class="px-6 py-3 font-semibold capitalize align-middle bg-transparent border-b border-gray-200 border-solid shadow-none tracking-none whitespace-nowrap text-slate-400"></th>
          </tr>
        </thead>
        <tbody>
          <% @customer.orders.latest.each do |order| %>
            <tr>
              <td class="p-3 align-middle bg-transparent border-b whitespace-nowrap shadow-transparent">
                <p class="font-semibold leading-tight text-md"><%= number_to_currency(order.billing_amount, unit: "¥", strip_insignificant_zeros: true) %></p>
              </td>
              <td class="p-3 leading-normal text-center align-middle bg-transparent border-b text-sm whitespace-nowrap shadow-transparent">
                <span class="bg-blue-100 text-blue-800 text-xs font-semibold p-2 rounded"><%= order.status %></span>
              </td>
              <td class="p-3 text-center align-middle bg-transparent border-b whitespace-nowrap shadow-transparent">
                <span class="font-semibold leading-tight text-md"><%= l order.created_at, format: :short %></span>
              </td>
              <td class="p-3 align-middle bg-transparent border-b whitespace-nowrap shadow-transparent">
                <%= link_to admin_order_path(order), class: "font-semibold leading-tight text-sm text-slate-400" do %>
                  詳細
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <% else %>
        <p>注文履歴はありません。</p>
      <% end %>
    </div>
  </div>
</div>