config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions: 'admin/sessions',
    registrations: 'admin/registrations'
  }
  devise_for :customers, controllers: {
    sessions: 'customer/sessions',
    registrations: 'customer/registrations'
  }

  # ルート追加（顧客用と管理者用）
  devise_scope :customer do
    post 'customers/guest_sign_in', to: 'customer/sessions#guest_sign_in', as: :guest_customer_sign_in
  end
  
  devise_scope :admin do
    post 'admins/guest_sign_in', to: 'admin/sessions#guest_sign_in', as: :guest_admin_sign_in
  end
  
  root to: 'pages#home'
  namespace :admin do
    root to: 'pages#home'
    resources :products, only: %i[index show new create edit update destroy]
    resources :orders, only: %i[show update]
    resources :customers, only: %i[index show update]
    authenticate :admin do
      mount Sidekiq::Web => '/sidekiq'
    end
  end

  scope module: :customer do
    resources :products, only: %i[index show] do
      resources :reviews, only: %i[index create]
    end
    resources :contacts, only: %i[new create]
    resources :cart_items, only: %i[index create destroy] do
      member do
        patch 'increase'
        patch 'decrease'
      end
    end
    resources :checkouts, only: [:create]
    post '/webhooks/stripe', to: 'webhooks#stripe'
    resources :orders, only: %i[index show] do
      collection do
        get 'success'
      end
    end
    resources :customers do
      collection do
        get 'confirm_withdraw'
        patch 'withdraw'
      end
    end
  end
  
  get '/up/', to: 'up#index', as: :up
  get '/up/databases', to: 'up#databases', as: :up_databases
  match '/500', to: 'application#render500', via: :all
  match '/404', to: 'application#render404', via: :all
  get 'test_render500', to: 'error/errors#test_render500'
end

app/models/product.rb
class Product < ApplicationRecord
  paginates_per 10
  with_options presence: true do
    validates :name
    validates :description
    validates :price
    validates :stock
    validates :image
  end
  has_one_attached :image
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  has_many :reviews, dependent: :destroy

  def avg_score
    if reviews.empty?
      0.0
    else
      reviews.average(:score).round(1).to_f
    end
  end

  def review_score_percentage
    if reviews.empty?
      0.0
    else
      reviews.average(:score).round(1).to_f * 100 / 5
    end
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_product, only: %i[show edit update destroy]

  def index
    @products = Product.page(params[:page]).per(10) # 1ページあたり10件を表示
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to admin_product_path(@product), notice: '商品が正常に作成されました。'
    else
      render :new
    end
  end

  def show; end

  def edit; end

  def update
    if @product.update(product_params)
      redirect_to admin_product_path(@product), notice: '商品が正常に更新されました。'
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to admin_products_path, notice: '商品が正常に削除されました。' }
    end
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :description, :price, :stock, :image)
  end
end

app/controllers/customer/products_controller.rb
class Customer::ProductsController < ApplicationController
  before_action :authenticate_customer!, only: [:show]
  def index
    @products = Product.page(params[:page]).per(9) # 1ページあたり9件を表示
  end

  def show
    @product = Product.find(params[:id])
    @cart_item = CartItem.new
    @review = Review.new
  end
end

app/helpers/customer/products_helper.rb
module Customer::ProductsHelper
end

app/views/admin/products/destroy.turbo_stream.erb
<turbo-stream action="remove" target="product-<%= @product.id %>"/>

app/views/admin/products/edit.html.erb
<div class="mb-6 text-center">
  <span class="text-3xl font-bold">
    商品編集
  </span>
</div>

<div class='flex flex-wrap justify-center'>
  <%= form_with model: @product, url: admin_product_path(@product), local: true, class: "xl:w-8/12 md:w-10/12", data: { turbo: false } do |f| %>
    <%= render "admin/shared/error_messages", resource: @product %>
    
    <div class="mb-6">
      <%= f.label :name, "商品名", class: "mb-2 block text-sm text-gray-600" %>
      <%= f.text_field :name, class: "w-full rounded-md border border-gray-300 py-2 px-3 placeholder:text-gray-300 focus:border-indigo-300 focus:outline-none focus:ring focus:ring-indigo-100", placeholder: "商品名を入力してください" %>
    </div>

    <div class="mb-6">
      <%= f.label :description, "詳細", class: "mb-2 block text-sm text-gray-600" %>
      <%= f.text_area :description, rows: "5", class: "w-full rounded-md border border-gray-300 py-2 px-3 placeholder:text-gray-300 focus:border-indigo-300 focus:outline-none focus:ring focus:ring-indigo-100", placeholder: "商品の詳細を入力してください" %>
    </div>

    <div class="mb-6">
      <%= f.label :price, "金額", class: "mb-2 block text-sm text-gray-600" %>
      <%= f.number_field :price, class: "w-full rounded-md border border-gray-300 py-2 px-3 placeholder:text-gray-300 focus:border-indigo-300 focus:outline-none focus:ring focus:ring-indigo-100", placeholder: "金額を入力してください" %>
    </div>

    <div class="mb-6">
      <%= f.label :stock, "在庫数", class: "mb-2 block text-sm text-gray-600" %>
      <%= f.number_field :stock, class: "w-full rounded-md border border-gray-300 py-2 px-3 placeholder:text-gray-300 focus:border-indigo-300 focus:outline-none focus:ring focus:ring-indigo-100", placeholder: "在庫数を入力してください" %>
    </div>

    <div class="mb-6">
      <%= f.label :image, "画像ファイル", class: "mb-2 block text-sm text-gray-600" %>
      <%= f.file_field :image, class: "block w-full px-3 py-1.5 text-base font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none" %>
    </div>

    <%= f.submit "更新", class: "inline-flex w-full items-center justify-center rounded-md bg-indigo-500 p-3 text-white duration-100 ease-in-out hover:bg-indigo-600 focus:outline-none" %>
  <% end %>
</div>

app/views/admin/products/index.html.erb
<div class="mb-8 text-center">
  <span class="text-3xl font-bold">
    商品一覧（管理画面）
  </span>
</div>

<div class="flex flex-wrap">
  <div class="flex-none w-full max-w-full px-6">
    <%= link_to new_admin_product_path, class: "mb-4 inline-flex items-center justify-center rounded-md bg-indigo-500 p-3 text-white duration-100 ease-in-out hover:bg-indigo-600 focus:outline-none" do %>
      新規商品登録
    <% end %>
    <div class="relative flex flex-col min-w-0 mb-6 break-words bg-white border-0 border-transparent border-solid shadow-soft-xl rounded-2xl bg-clip-border">
      <div class="flex-auto px-0 pt-0 pb-2">
        <div class="p-0 overflow-x-auto">
          <table class="items-center w-full mb-0 align-top border-gray-200 text-slate-500">
            <thead class="align-bottom">
              <tr>
                <th class="px-6 py-3 font-bold text-left uppercase align-middle bg-transparent border-b border-gray-200 shadow-none text-xxs border-b-solid tracking-none whitespace-nowrap text-slate-400 opacity-70">商品名&画像</th>
                <th class="px-6 py-3 pl-2 font-bold text-left uppercase align-middle bg-transparent border-b border-gray-200 shadow-none text-xxs border-b-solid tracking-none whitespace-nowrap text-slate-400 opacity-70">金額</th>
                <th class="px-6 py-3 font-center uppercase align-middle bg-transparent border-b border-gray-200 shadow-none text-xxs border-b-solid tracking-none whitespace-nowrap text-slate-400 opacity-70">在庫数</th>
                <th class="px-6 py-3 font-center uppercase align-middle bg-transparent border-b border-gray-200 shadow-none text-xxs border-b-solid tracking-none whitespace-nowrap text-slate-400 opacity-70">作成日時</th>
                <th class="px-6 py-3 font-center uppercase align-middle bg-transparent border-b border-gray-200 shadow-none text-xxs border-b-solid tracking-none whitespace-nowrap text-slate-400 opacity-70">更新日時</th>
                <th class="px-6 py-3 font-semibold capitalize align-middle bg-transparent border-b border-gray-200 border-solid shadow-none tracking-none whitespace-nowrap text-slate-400 opacity-70"></th>
              </tr>
            </thead>
            <tbody>
              <% @products.each do |product| %>
                <tr id="product-<%= product.id %>">
                  <td class="p-2 align-middle bg-transparent border-b whitespace-nowrap shadow-transparent">
                    <%= link_to admin_product_path(product) do %>
                      <div class="flex px-2 py-1">
                        <div class="w-16 mr-5">
                          <%= image_tag product.image, class: "inline-flex items-center justify-center mr-4 text-white transition-all duration-200 ease-soft-in-out text-sm rounded-full object-fill" %>
                        </div>
                        <div class="flex flex-col justify-center">
                          <h6 class="text-lg font-bold"><%= product.name %></h6>
                        </div>
                      </div>
                    <% end %>
                  </td>
                  <td class="p-2 align-middle bg-transparent border-b whitespace-nowrap shadow-transparent">
                    <p class="font-semibold leading-tight text-sm"><%= number_to_currency(product.price, unit: "¥", strip_insignificant_zeros: true) %></p>
                  </td>
                  <td class="p-2 text-center align-middle bg-transparent border-b whitespace-nowrap shadow-transparent">
                    <span class="font-semibold leading-tight text-sm text-slate-400"><%= product.stock %></span>
                  </td>
                  <td class="p-2 text-center align-middle bg-transparent border-b whitespace-nowrap shadow-transparent">
                    <span class="font-semibold leading-tight text-sm text-slate-400"><%= l product.created_at, format: :short %></span>
                  </td>
                  <td class="p-2 text-center align-middle bg-transparent border-b whitespace-nowrap shadow-transparent">
                    <span class="font-semibold leading-tight text-sm text-slate-400"><%= l product.updated_at, format: :short %></span>
                  </td>
                <td class="p-2 align-middle bg-transparent border-b whitespace-nowrap shadow-transparent">
                  <%= link_to edit_admin_product_path(product), class: "inline-block font-semibold leading-tight text-xs text-white bg-gradient-to-r from-cyan-500 to-indigo-700 hover:from-cyan-500 hover:to-indigo-700 rounded-lg py-1 px-2 shadow transition duration-300" do %>
                    更新
                  <% end %> 
                  <%= link_to '削除', admin_product_path(product), data: { turbo_method: :delete, turbo_confirm: "削除してもよろしいですか?" }, class: "inline-block font-semibold leading-tight text-xs text-white bg-gradient-to-r from-pink-400 to-purple-700 hover:from-pink-400 hover:to-purple-800 rounded-lg py-1 px-2 shadow transition duration-300" %> 
                </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

<%# ページネーションを表示する %>
<%= paginate @products %>

app/views/admin/products/new.html.erb
<div class="mb-6 text-center">
  <span class="text-3xl font-bold">
    新規商品登録
  </span>
</div>

<div class='flex flex-wrap justify-center'>
  <%= form_with model: @product, url: admin_products_path, local: true, class: "xl:w-8/12 md:w-10/12", data: { turbo: false } do |f| %>
    <%= render "admin/shared/error_messages", resource: @product %>
    
    <div class="mb-6">
      <%= f.label :name, "商品名", class: "mb-2 block text-sm text-gray-600" %>
      <%= f.text_field :name, class: "w-full rounded-md border border-gray-300 py-2 px-3 placeholder:text-gray-300 focus:border-indigo-300 focus:outline-none focus:ring focus:ring-indigo-100", placeholder: "商品名を入力してください" %>
    </div>

    <div class="mb-6">
      <%= f.label :description, "詳細", class: "mb-2 block text-sm text-gray-600" %>
      <%= f.text_area :description, rows: "5", class: "w-full rounded-md border border-gray-300 py-2 px-3 placeholder:text-gray-300 focus:border-indigo-300 focus:outline-none focus:ring focus:ring-indigo-100", placeholder: "商品の詳細を入力してください" %>
    </div>

    <div class="mb-6">
      <%= f.label :price, "金額", class: "mb-2 block text-sm text-gray-600" %>
      <%= f.number_field :price, class: "w-full rounded-md border border-gray-300 py-2 px-3 placeholder:text-gray-300 focus:border-indigo-300 focus:outline-none focus:ring focus:ring-indigo-100", placeholder: "金額を入力してください" %>
    </div>

    <div class="mb-6">
      <%= f.label :stock, "在庫数", class: "mb-2 block text-sm text-gray-600" %>
      <%= f.number_field :stock, class: "w-full rounded-md border border-gray-300 py-2 px-3 placeholder:text-gray-300 focus:border-indigo-300 focus:outline-none focus:ring focus:ring-indigo-100", placeholder: "在庫数を入力してください" %>
    </div>

    <div class="mb-6">
      <%= f.label :image, "画像ファイル", class: "mb-2 block text-sm text-gray-600" %>
      <%= f.file_field :image, class: "block w-full px-3 py-1.5 text-base font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none" %>
    </div>

    <%= f.submit "新規作成", class: "inline-flex w-full items-center justify-center rounded-md bg-indigo-500 p-3 text-white duration-100 ease-in-out hover:bg-indigo-600 focus:outline-none cursor-pointer" %>
  <% end %>
</div>

app/views/admin/products/show.html.erb
<div class="mb-8 text-center">
  <span class="text-3xl font-bold">
    商品詳細
  </span>
</div>

<div class="relative mx-auto max-w-screen-xl p-6">
  <div class="grid grid-cols-1 items-start gap-9 md:grid-cols-2">
    <div>
      <%= image_tag @product.image, class: "aspect-square w-full rounded-xl object-cover" %>
    </div>

    <div class="sticky top-0">
      <div class="flex flex-col justify-between">
        <div class="flex justify-between mb-6">
          <div class="max-w-[35ch]">
            <h1 class="text-2xl font-bold">
              <%= @product.name %>
            </h1>
          </div>
          <p class="text-2xl font-bold"><%= number_to_currency(@product.price, unit: "¥", strip_insignificant_zeros: true) %></p>
        </div>

        <div class="mb-8">
          <p>
            <%= @product.description.gsub("\n", "<br>").html_safe %>
          </p>
        </div>

        <div class="flex">
          <div>
            <% if @product.stock > 0 %>
              <span class="bg-blue-100 text-blue-800 text-sm font-semibold p-2.5 rounded">在庫数 (<%= @product.stock %>)</span>
            <% else %>
              <span class="bg-red-100 text-red-800 text-sm font-semibold p-2.5 rounded">Out of stock</span>
            <% end %>
          </div>
          <div class="ml-4">
          <%= link_to edit_admin_product_path(@product), class: "text-center cursor-pointer focus:outline-none text-white bg-green-700 hover:bg-green-800 focus:ring-4 focus:ring-green-300 font-medium rounded-lg text-sm px-5 py-2.5 mb-2" do %>
            商品更新
          <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>